services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=kanata
      - DB_NAME=piutang

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=piutang
      - MYSQL_ROOT_PASSWORD=kanata
    volumes:
      - mysql_data:/var/lib/mysql
      - ./piutang.sql:/docker-entrypoint-initdb.d/piutang.sql

volumes:
  mysql_data: 